# Site
title:          Alex Haldeman
bio:            'Software Engineer'
description:    "Simple Jekyll theme for your blog by Taylan Tatlı"
picture:        'assets/img/headshot.JPG'
locale:         en_US
url:            http://ahaldeman.github.io
baseurl:        /
# Jekyll
permalink:      /:title/
markdown:       kramdown
highlighter:    rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed

github: ahaldeman
#stackoverflow: none
linkedin: alexander-haldeman-09a7aa63

# Paginate
# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: /

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
